# Service composition file for Docker Compose or Podman Compose
# https://cratedb.com/docs/guide/integrate/mysql/

services:

  cratedb:
    image: docker.io/crate:latest
    command: >
      crate -Cdiscovery.type=single-node
    ports:
      - "4200:4200/tcp"
      - "5432:5432/tcp"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/"]
      interval: 5s
      timeout: 30s
      retries: 5

  mariadb:
    image: docker.io/mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: secret
    ports:
      - "3306:3306/tcp"

  ctk-ingest:
    image: ghcr.io/crate/cratedb-toolkit-ingest:latest
    profiles: ["cli"]
